version: '3.8'

services:
###> doctrine/doctrine-bundle ###
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=mysql://maryel-n_a:Admin0125!@db:3306/maryel-n_movies?serverVersion=10.11.2-MariaDB&charset=utf8mb4
      - MESSENGER_TRANSPORT_DSN=doctrine://default?auto_setup=0
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: movies_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: maryel-n_movies
      MYSQL_USER: maryel-n_a
      MYSQL_PASSWORD: Admin0125!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: